profile=gpu-hq
video-sync=display-resample
hr-seek-framedrop=no
hwdec=auto

# Disable built-in OSC (replaced by uosc)
osc=no
osd-bar=no

# Default volume
volume=50

# Start with built-in interpolation by default
interpolation=yes
tscale=oversample
