profile=gpu-hq
video-sync=display-resample
hr-seek-framedrop=no

# Disable built-in OSC (replaced by uosc)
osc=no
osd-bar=no

# Start with built-in interpolation by default
interpolation=yes
tscale=oversample
